### ISSUE TITLE
Stop Program from Exiting Every Hour or So

### ISSUE THREAD

**Issue by kb1lqc** [FaradayRF/clerk#6]
## Summary
Make this program more robust, It seems to exit often. Maybe I should log to file as well so I can figure out what goes wrong easier.

## Problem Explanation
For some reason the program exits every hour or so. I am not sure if it is running out of memory or a network connection is failing. Need to investigate more.

# Supporting Information
>This is a handy spot to post any screenshots or file outputs in order to better support this issue. We want to keep the top of the ticket clutter-free as possible.

**Comment by kb1lqc** [comment]
Well there we go. I installed grafana and influxdb on my windows machine and within a few minutes this happened.
![image](https://user-images.githubusercontent.com/331540/30897713-8cf6c064-a30c-11e7-9822-8ff32a4ce199.png)

Looks like aprslib is dropping the connection. Time to make it reliable!

**Comment by kb1lqc** [comment]
Hey @rossengeorgiev what is the best way to still use the consumer but deal with connection drops to APRS-IS? As far as I can tell I'd need to modify your code to deal with this and still use the consumer? Pretty sure immortal is meant for this but I am observing network failures which are not recoverable without restarting script.

**Comment by rossengeorgiev** [comment]
@kb1lqc set `immortal=True`

https://github.com/rossengeorgiev/aprs-python/blob/b6d67fd66dda5f9f405f7634b9f67744bb4016bb/aprslib/inet.py#L160-L171

Sadly it doesn't seem to be mentioned in the docs. Or if you are doing more stuff than just consuming packets, you might want to handle the exceptions yourself and you can use the following as reference:

https://github.com/rossengeorgiev/aprs-python/blob/b6d67fd66dda5f9f405f7634b9f67744bb4016bb/aprslib/inet.py#L196-L203

**Comment by kb1lqc** [comment]
Fixed a bunch of stuff in 46ed4ad825e5a444e29a3e3d483c704818ccaa08

However, looks like no database error also extends to parsing so need to fix that.
![image](https://user-images.githubusercontent.com/331540/30903110-792527d6-a322-11e7-914d-d3de54a1d69a.png)

**Comment by kb1lqc** [comment]
I'm actually still seeing connections not reestablish with immortal on too

---- On Wed, 27 Sep 2017 01:05:43 -0700 notifications@github.com wrote ----

@kb1lqc set immortal=True

https://github.com/rossengeorgiev/aprs-python/blob/b6d67fd66dda5f9f405f7634b9f67744bb4016bb/aprslib/inet.py#L160-L171

Sadly it doesn't seem to be mentioned in the docs.

**Comment by rossengeorgiev** [comment]
@kb1lqc any errors? exceptions? log?

**Comment by kb1lqc** [comment]
I can provide logs later but it's errno 10054 I believe. Connection dropped by host

---- On Wed, 27 Sep 2017 09:34:33 -0700 notifications@github.com wrote ----

@kb1lqc any errors? exceptions? log?

**Comment by rossengeorgiev** [comment]
Do you get disconnected on a regular interval, such as 2hrs ?

**Comment by kb1lqc** [comment]
So far I've noticed it's about 30 minutes to an hour after connecting the consumer to rotate.aprs.is

---- On Wed, 27 Sep 2017 11:07:18 -0700 notifications@github.com wrote ----

Do you get disconnected on a regular interval, such as 2hrs ?

**Comment by kb1lqc** [comment]
@rossengeorgiev here's the error:

```ERROR:aprslib.inet.IS:socket error on recv(): [Errno 10054] An existing connection was forcibly closed by the remote host
```

Just repeats in a loop quickly printing to screen:
![image](https://user-images.githubusercontent.com/331540/30948675-62b443ac-a3c6-11e7-8591-29dbb87bed13.png)

**Comment by kb1lqc** [comment]
@rossengeorgiev you can also see it lasts about 44 minutes this morning until the connection was closed. This was data being extracted from APRS-IS

![image](https://user-images.githubusercontent.com/331540/30948702-98bc0dd6-a3c6-11e7-8a50-b5675dbbcc72.png)

**Comment by rossengeorgiev** [comment]
Some APRS servers have a setting to kickoff clients that have not send any data for period of time. By default is 2hrs, but it could be changed. Still, that error should cause a reconnect, with `immortal=True`. What version of aprslib, python, OS are you using?

**Comment by kb1lqc** [comment]
aprslib==0.6.46

**Comment by kb1lqc** [comment]
Running on both windows 7 as well as on a Debian 9 server (Digital Ocean)

**Comment by kb1lqc** [comment]
Per @rossengeorgiev suggestion I think I'm going to try a few paths forward:

- [Send a status packet](https://aprs-python.readthedocs.io/en/stable/examples.html#sending-a-packet) once every 30 minutes. Per [aprsc timers and timeout configuration](http://he.fi/aprsc/CONFIGURATION.html) many aprs servers will disconnect a station that doesn't transmit to it.
- Setup a local aprsc running on FaradayRF servers for this client to connect to. Disable the timeout feature if possible.

**Comment by kb1lqc** [comment]
@rossengeorgiev when I run the consumer it is an infinite loop (obviously). There's no obvious way to run code to periodically send a status message other than using a separate thread. Am I missing something?

**Comment by rossengeorgiev** [comment]
@kb1lc yeah, you can say its an infinite loop. I would setup logging to debug level, change the format to include timestamp, set `raw=True`, set logging to file and console and let the code run for a while until it encounters the issue. Then we can see what happened. The above error log doesn't make sense, perhaps you set logging to just ERROR level, which won't show INFO log messages. Ideally you want it as INFO, or DEBUG.

**Comment by kb1lqc** [comment]
I think it was APRS-IS servers kicking me off for inactivity. I enabled two threads 1) a heartbeat and 2) your consumer. Both use the same APRS-IS connection so the idea is the heartbeat keeps it alive. Seems to be working. I send one heartbeat out every 15 minutes:

https://aprs.fi/?c=raw&call=KB1LQC&limit=50&view=normal
![image](https://user-images.githubusercontent.com/331540/31022551-f80c0282-a4ed-11e7-8e54-3a9acf3baaac.png)

This seems to be working. My connections are still alive 8 hours later:
![image](https://user-images.githubusercontent.com/331540/31022618-29c3083e-a4ee-11e7-8392-09505b433478.png)

I think the oddness comes from your consumer getting kicked off. I think setting up a local aprsc server and setting the timeout to be 30 seconds or something would help investigate this issue quickly.

Why would I want to set raw=True @rossengeorgiev? Yes I should investigate changing the logging level and output. I'd also like to log to file as I often lose internet at my house and SSH connections are lost so I miss the output.

**Comment by rossengeorgiev** [comment]
I add automatic ping in the consumer to prevent this issue. You don't really need to send a valid packet, you could just send `#ping`, which gets dropped but is counted as data.

If your connection is dropping at home often i suggest looking at `tmux` and `mosh`

**Comment by kb1lqc** [comment]
Fixed by #11
